security:
  oauth2:
    client:
      clientId: cai-account
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://cai-security:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: cai-account-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: eodessa
      port: 27017

server:
  context-path: /accounts
  port: 6000